require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

platform :ios, '11.0'

target 'MyHeroApp' do
  config = use_native_modules!
  rn_maps_path = '../node_modules/react-native-maps'

  use_react_native!(:path => config["reactNativePath"])

  pod 'RNGestureHandler', :path => '../node_modules/react-native-gesture-handler'

  pod 'react-native-maps', :path => '../node_modules/react-native-maps'

  pod 'RNSVG', :path => '../node_modules/react-native-svg'

  pod 'react-native-geolocation', :path => '../node_modules/@react-native-community/geolocation'

  pod 'RNCCheckbox', :path => '../node_modules/@react-native-community/checkbox'

  pod "Yoga", :path => "../node_modules/react-native/ReactCommon/yoga"

  pod 'GoogleMaps', '4.0.0'

  pod 'Google-Maps-iOS-Utils', '2.1.0'
  
  pod 'GoogleUtilities', '5.3.7'

  pod 'GoogleAppMeasurement', '5.4'

  pod 'GooglePlaces', '4.0.0'
  
  pod 'RNCAsyncStorage', :path => '../node_modules/@react-native-community/async-storage'

  pod 'react-native-image-picker', :path => '../node_modules/react-native-image-picker'

  pod 'RNLocalize', :path => '../node_modules/react-native-localize'

  pod 'react-native-background-timer', :path => '../node_modules/react-native-background-timer'

  pod 'GoogleWebRTC'
  
  pod 'react-native-webrtc', :path => '../node_modules/react-native-webrtc'

  pod 'React-RCTPushNotification', :path => '../node_modules/react-native/Libraries/PushNotificationIOS'


  target 'MyHeroAppTests' do
    inherit! :complete
    # Pods for testing
  end

  # Enables Flipper.
  #
  # Note that if you have use_frameworks! enabled, Flipper will not work and
  # you should disable these next few lines.
  use_flipper!
  post_install do |installer|
    flipper_post_install(installer)
  end
end

target 'MyHeroApp-tvOS' do
  # Pods for MyHeroApp-tvOS

  target 'MyHeroApp-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end
end
